CREATE TABLE Staging (
	Project_Hierarchy VARCHAR (255),
	Project VARCHAR (255),
	Project_Group VARCHAR (255),
	Worker_Name VARCHAR (255),
	Worker_ID VARCHAR (255),
	Worker_Status VARCHAR (255),
	Worker_Type VARCHAR (255),
	Resource_Manager VARCHAR (255),
	Resource_Cost_Center VARCHAR (255),
	Reported_Date DATE,
	Project_Phase VARCHAR (255),
	Project_Task VARCHAR (255),
	Approved_Hours FLOAT8,
	Worker_Rate FLOAT8,
	Worker_Total_Cost FLOAT8,
	Worker_Comments VARCHAR (255),
	Application VARCHAR (255),
	Application_ID VARCHAR (255),
	Customer_Input_Task VARCHAR (255),
	RPS_Plan_Number VARCHAR (255)
);
